### ISSUE TITLE
Looping music?

### ISSUE THREAD

**Issue by Prostar30** [megalon/nick-custom-music-mod#5]
If its possible, it would be nice if you could add the ability to add loop points to songs so you don't have to make a 15 minute MP3 file and just paste loop points from smashcustommusic. Otherwise, great work on this mod! It's been very good so far.

**Comment by megalon** [comment]
This feature has been added as of #14 
And is included in [release v1.3.1](https://github.com/megalon/nick-custom-music-mod/releases/tag/v1.3.1)!
